# Installs zabbix-proxy
class profiles::zabbixproxy (
    $DBPassword,
    $Hostname=$::fqdn,
    $zabbix_version='2.2',
    $manage_database=true,
    $ProxyMode=0,
    $Server='10.41.2.101',
    $LogFile='/var/log/zabbix/zabbix_proxy.log',
    $LogFileSize=256,
    $PidFile='/var/run/zabbix/zabbix_proxy.pid',
    $DBHost='localhost',
    $DBName='zabbix20',
    $DBUser='zabbix20_adm',
    $DBSocket='/db/mysql/datadir/mysqld.sock',
    $DBPort=3306,
    $ProxyOfflineBuffer=168,
    $ConfigFrequency=120,
    $DataSenderFrequency=30,
    $StartPollers=150,
    $StartIPMIPollers=3,
    $StartTrappers=20,
    $StartPingers=50,
    $StartDiscoverers=5,
    $CacheSize=137438953472,
    $StartDBSyncers=8,
    $HistoryCacheSize=549755813888,
    $Timeout=30,
    $UnreachablePeriod=90,
    $ExternalScripts='/etc/zabbix/eternalscripts',
    $FpingLocation='/usr/bin/fping',
    $SSHKeyLocation='/etc/zabbix/ssh-key',
    $LogSlowQueries=60000,
  ){
  class { 'sudo::params':
    requiretty => false,
  }
  class { 'mysql::server':
    root_password => 'password',
  }
  class { 'zabbix::proxy':
    zabbix_version     => $zabbix_version,
    manage_database    => $manage_database,
    dbtype             => 'mysql',
    mode               => $ProxyMode,
    zabbix_server_host => $Server,
    logfile            => $LogFile,
    logfilesize        => $LogFileSize,
    pidfile            => $PidFile,
    dbhost             => $DBHost,
    dbname             => $DBName,
    dbuser             => $DBUser,
    dbpassword         => $DBPassword,
    dbsocket           => $DBSocket,
    dbport             => $DBPort,
    offlinebuffer      => $ProxyOfflineBuffer,
    configfrequency    => $ConfigFrequency,
    datasederfrequency => $DataSenderFrequency,
    startpollers       => $StartPollers,
    startipmipollers   => $StartIPMIPollers,
    starttrappers      => $StartTrappers,
    startpingers       => $StartPingers,
    startdiscoverers   => $StartDiscoverers,
    cachesize          => $CacheSize,
    startdbsyncers     => $StartDBSyncers,
    historycachesize   => $HistoryCacheSize,
    timeout            => $Timeout,
    unreachableperiod  => $UnreachablePeriod,
    externalscripts    => $ExternalScripts,
    fpinglocation      => $FpingLocation,
    sshkeylocation     => $SSHKeyLocation,
    logslowqueries     => $LogSlowQueries,
  }
}
